import{CalendarDays,Users,Workflow,ChartNoAxesCombined,BrainCircuit,Building2,ListChecks,ClipboardCheck,Send,FileStack,Waypoints,MonitorUp,PlugZap,Inbox,LayoutDashboard,ShieldCheck,ArrowRightLeft}from'lucide-react';
export const modules=[
{slug:'scheduler',name:'Scheduler',group:'Coordinate care',icon:CalendarDays,kicker:'Intelligent appointment orchestration',headline:'Match the right patient to the right care—without the scheduling friction.',description:'Coordinate providers, services, rooms, locations, forms, reminders, and downstream workflows from one intelligent scheduling engine.',outcomes:['Eliminate preventable booking conflicts','Coordinate every resource in real time','Turn each booking into a complete workflow'],features:['Multi-location calendar views','Recurring and complex appointments','Room and service validation','Automated reminders and forms'],accent:'#1179e8'},
{slug:'planner',name:'Planner',group:'Coordinate care',icon:Waypoints,kicker:'Proactive capacity planning',headline:'Design appointment capacity before demand reaches your calendar.',description:'Shape availability around provider preferences, patient priority, service demand, and operational goals—then let Scheduler execute the plan.',outcomes:['Balance provider workloads','Reserve access for priority patients','Release unused capacity automatically'],features:['Provider and service preferences','Weighted priority allocation','Capacity release rules','Demand-aware recommendations'],accent:'#0aa69a'},
{slug:'queue-management',name:'Queue Management',group:'Coordinate care',icon:ListChecks,kicker:'Live patient flow',headline:'See and coordinate every patient journey as it happens.',description:'Give reception, providers, and managers one live operational view from arrival and check-in through room assignment, consultation, and departure.',outcomes:['Reduce waiting-room uncertainty','Respond to delays before they spread','Keep rooms and providers moving'],features:['Real-time patient statuses','Flexible queue prioritization','Room assignment','Walk-in management'],accent:'#df6e4f'},
{slug:'patients',name:'Patients',group:'Engage patients',icon:Users,kicker:'Longitudinal patient operations',headline:'One connected record for every operational patient interaction.',description:'Bring appointments, forms, referrals, documents, communications, portal access, and operational history into one secure patient workspace.',outcomes:['One patient, one operational record','Eliminate fragmented context','Support continuity across every team'],features:['New patient intake','Patient categories','Communication history','Portal access management'],accent:'#7a65dc'},
{slug:'patient-portal',name:'Patient Portal',group:'Engage patients',icon:MonitorUp,kicker:'Connected patient self-service',headline:'Give patients clarity and control throughout their care journey.',description:'A secure, mobile-ready destination for booking, digital check-in, forms, messages, referrals, notifications, and documents.',outcomes:['Reduce administrative calls','Increase pre-visit completion','Keep patients informed'],features:['Self-service appointments','Digital check-in','Secure messaging','Referral tracking'],accent:'#13a27f'},
{slug:'forms',name:'Forms',group:'Engage patients',icon:ClipboardCheck,kicker:'Intelligent digital data collection',headline:'Turn paperwork into structured, automated healthcare workflows.',description:'Create, assign, complete, review, and securely store configurable forms that connect directly to patient journeys and operational events.',outcomes:['Eliminate paper workflows','Improve data quality','Make submissions immediately actionable'],features:['Visual form builder','Conditional logic','Digital consent','Version management'],accent:'#306ad8'},
{slug:'referrals',name:'Referrals',group:'Orchestrate work',icon:ArrowRightLeft,kicker:'End-to-end referral coordination',headline:'Move every referral from receipt to care without losing visibility.',description:'Receive, process, assign, track, and complete incoming and outgoing referrals in one structured, connected workflow.',outcomes:['Prevent lost referrals','Accelerate time to care','Give teams and patients visibility'],features:['Incoming and outgoing referrals','Assignment and routing','Status lifecycle','Document management'],accent:'#cc5b73'},
{slug:'automation',name:'Automation',group:'Orchestrate work',icon:Workflow,kicker:'Event-driven workflow orchestration',headline:'Make the next operational step happen automatically.',description:'Connect events, conditions, and actions across Migranium and external systems so routine work is completed consistently without staff intervention.',outcomes:['Remove repetitive administration','Standardize critical workflows','Scale operations without scaling busywork'],features:['Visual workflow structure','Reusable templates','Cross-module actions','Execution monitoring'],accent:'#3d79e6'},
{slug:'task-manager',name:'Task Manager',group:'Orchestrate work',icon:FileStack,kicker:'Context-rich work execution',headline:'Make every responsibility visible, owned, and connected.',description:'Centralize all non-appointment work and keep tasks connected to the patient, referral, fax, message, or event that created them.',outcomes:['No work lost between systems','Clear accountability','Complete operational context'],features:['All Tasks workspace','Priority and ownership','Team collaboration','AI-assisted assignment'],accent:'#8b60d6'},
{slug:'fax',name:'Fax',group:'Orchestrate work',icon:Inbox,kicker:'Intelligent document intake',headline:'Transform healthcare fax from an inbox into an operational workflow.',description:'Receive, classify, match, route, and send healthcare documents digitally with AI assistance and complete auditability.',outcomes:['Reduce manual document handling','Accelerate referral intake','Make every fax traceable'],features:['OCR and classification','Patient matching','Referral detection','Secure outbound fax'],accent:'#2b8caa'},
{slug:'messaging',name:'Messaging',group:'Engage patients',icon:Send,kicker:'Contextual patient communication',headline:'Deliver the right message at the right moment in the journey.',description:'Centralize templates, campaigns, delivery monitoring, and patient communication history across email, SMS, portal, and workflow events.',outcomes:['Reduce missed appointments','Communicate consistently at scale','See every delivery outcome'],features:['Dynamic templates','Targeted campaigns','Automated messaging','Communication history'],accent:'#0f968d'},
{slug:'analytics',name:'Analytics',group:'Understand operations',icon:ChartNoAxesCombined,kicker:'Unified operational intelligence',headline:'Understand the entire organization—not another isolated report.',description:'Turn scheduling, queue, referrals, messaging, forms, tasks, automation, and AI activity into one continuously updated view of performance.',outcomes:['Find bottlenecks earlier','Balance capacity with evidence','Measure the value of automation'],features:['Cross-module reporting','Filtering and segmentation','Operational dashboards','AI usage analytics'],accent:'#225fd0'},
{slug:'kemi',name:'Kemi AI',group:'Intelligence',icon:BrainCircuit,kicker:'Embedded operational intelligence',headline:'From question to action, without the busywork.',description:'Kemi understands organizational context, permissions, knowledge, and workflows to retrieve answers, complete tasks, and coordinate specialized AI agents.',outcomes:['Reduce time spent searching','Complete complex tasks conversationally','Surface operational risks early'],features:['Context-aware conversations','AI-powered search','Manage Agents','Decision support'],accent:'#19ad9c'},
{slug:'workplace',name:'Workplace',group:'Platform foundation',icon:Building2,kicker:'Your operational source of truth',headline:'Model how your healthcare organization actually works.',description:'Define the locations, providers, rooms, services, teams, roles, partners, and rules that every Migranium workflow depends on.',outcomes:['Configure once, use everywhere','Scale across locations','Govern access centrally'],features:['Locations and rooms','Providers and services','Roles and permissions','Organization settings'],accent:'#2975cb'},
{slug:'display',name:'Display',group:'Coordinate care',icon:LayoutDashboard,kicker:'Real-time patient information',headline:'Turn live operations into a calmer waiting experience.',description:'Present privacy-controlled queue status, wait estimates, check-in instructions, room calls, and announcements across waiting-room displays.',outcomes:['Reduce reception interruptions','Give patients useful visibility','Support self-service check-in'],features:['Live waitlist','Flexible layouts','QR code check-in','Privacy controls'],accent:'#5270c8'},
{slug:'integrations',name:'Integrations',group:'Platform foundation',icon:PlugZap,kicker:'Healthcare interoperability',headline:'Keep your systems. Connect the work between them.',description:'Synchronize Migranium with EMRs, fax, telephony, signatures, email, calendars, and custom systems through one governed connectivity layer.',outcomes:['Protect existing technology investments','Eliminate duplicate entry','Create cross-system workflows'],features:['EMR connectivity','Cloud fax and telephony','Email and calendar sync','Custom integrations'],accent:'#126ead'}];
export const integrations=[['EMR','Epic','OSCAR Pro','Accuro','Cerner'],['Communication','Microsoft 365','Google Workspace','3CX'],['Documents','iFax','Unite Fax','DocuSign'],['Productivity','Google Calendar','Outlook Calendar','Custom APIs']];
export const groups=['Coordinate care','Orchestrate work','Engage patients','Understand operations','Intelligence','Platform foundation'];
export const trust=[{icon:ShieldCheck,title:'Built for healthcare trust',text:'Role-based access, audit histories, encryption, and configurable governance throughout every workflow.'}];
